### ISSUE TITLE
Add XMonad.DBus to xmonad-contrib

### ISSUE THREAD

**Issue by dkasak** [troydm/xmonad-dbus#1]
Have you thought about upstreaming the `XMonad.DBus` module to xmonad-contrib? It would make this easier to package and it seems like a good addition.

**Comment by troydm** [comment]
@dkasak I'm not sure about what is a procedure for it to become part of xmonad-contrib, plus xmonad-dbus is partly a hackage XMonad module and partly an standalone app xmonad-dbus that is used in combination with it so I'm not sure how to package it as part of xmonad-contrib

**Comment by troydm** [comment]
this package is now added to hackage so you can easily use it as additional dependency when building your XMonad configuration
