### ISSUE TITLE
Add to Hackage

### ISSUE THREAD

**Issue by malte-v** [troydm/xmonad-dbus#3]
There already is an issue about adding this to xmonad-contrib, but as you said, the executable part of this package doesn't quite fit in there. Why not just upload xmonad-dbus to Hackage as-is? That way you can easily install both the executable and the library.

**Comment by malte-v** [comment]
If you want, I can do the upload and add you as a maintainer afterwards. I would need your Hackage handle for that.

**Comment by troydm** [comment]
@malte-v https://hackage.haskell.org/package/xmonad-dbus-0.1.0.0

**Comment by malte-v** [comment]
Thanks!
