### ISSUE TITLE
README: Istructions for installing from AUR (and other non-dev's)

### ISSUE THREAD

**Issue by PRESFIL** [troydm/xmonad-dbus#6]
Would you like to add a section on non-stack installation, for the AUR user?

I seem to be finally able to generate a working PKGBUILD for your program
(it may have been on the AUR before, but I didn't catch it), thanks to `arch-hs`.

I can contribute PKGBUILD to your repository, or only to the AUR.

**Comment by troydm** [comment]
@PRESFIL sure you can open PR and I'll take a look

**Comment by PRESFIL** [comment]
There are a few problems here before I can do a proper PR:

1. [x] For meaningful versions `-git` PKGBUILD, it is necessary that the repository contains
    tags with revisions. Could you import them?

2. [X] To build a `-git` package, you also need a cabal-file. I imported it from Hackage manually,
    but it doesn't seem to be the right way. You need to add `xmonad-dbus.cabal` to the repository,
    as done in `xmonad`, `xmobar` and other projects.

**Comment by troydm** [comment]
@PRESFIL I've added cabal file and tagged last version, does this suffice?

**Comment by PRESFIL** [comment]
This is suffice, but now, by looking at the content of the commit and hackage releases,
you have a inconsistency in tags. I assumed that your tags would be placed like this:

- `v0.1.0.1` 248c472dad99fd001c856e9d36c4e82adeaff0a9 "v0.1.0.1 - unicode related bug fixed"
- `v0.1.0.0` 253bd917c511951ca038036ef304514b13383843 "Initial commit"

Then it will look like this:

![image](https://user-images.githubusercontent.com/20644917/161586146-f7fcf916-2408-4cfb-a123-4c47c26a2351.png)

I achieved this by doing:

```sh
git tag --force v0.1.0.0 253bd91
git tag --force v0.1.0.1 248c472
git push --tags --force origin
```

**Comment by troydm** [comment]
@PRESFIL did same thing, check now

**Comment by PRESFIL** [comment]
:+1: perfect!

**Comment by troydm** [comment]
@PRESFIL merged, thx!
