### ISSUE TITLE
new release including cabal project file

### ISSUE THREAD

**Issue by anthraxx** [troydm/xmonad-dbus#8]
Hi there,

Thank you very much for this project. I'd like to request if you can create a new git tag and hackage release containing the latest commit which includes the project cabal file?

That would be very much welcome so I could more easily package this.

PS: would this maybe be a good idea for submitting as inclusion to xmonad-contrib?

**Comment by troydm** [comment]
there is git tag with release number, there aren't any major changes between current repository state and latest hackage version, only readme file, why do you need another hackage version?

**Comment by anthraxx** [comment]
Well there is the cabal file that we'd need to make use of: https://github.com/troydm/xmonad-dbus/commit/73a640bd2e2e0109347337556e0ecfc71b0e7848 and that is not contained in the release.

**Comment by troydm** [comment]
ahh okey, done, check v0.1.0.2 release
