### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ironlungx** [troydm/xmonad-dbus#9]
I am using the module in polybar. This is the module config:
```ini
[module/layout]
type = custom/script
exec = xmonad-dbus
interval = 5
tail = true
```

and this is parts of my xmonad.hs:
```hs
myLogHook :: DC.Client -> PP
myLogHook dbus = def { 
    ppOutput = D.send dbus 
    
-- Print icons based on the layout
  , ppLayout = 
        \layout -> case layout of
          "Spacing ResizableTall"        -> "\985629 "
          "Spacing Mirror ResizableTall" -> "\986732 "
          "Spacing Full"                 -> "\986719 " 
          _                              -> "\985629 "

  -- Disable Everything apart from layout
  , ppTitle   = const ""
  , ppCurrent = const ""
  , ppVisible = const "" 
  , ppHidden  = const ""
}
```

While idling it's taking up 15% CPU
![image](https://github.com/user-attachments/assets/e380eea2-8e94-4880-b05e-5930406dc784)

**Comment by troydm** [comment]
strange, are you sure that xmonad-dbus is the culprit, does your cpu usage goes down if you stop using it, it works following way, xmonad sends dbus messages via xmonad-dbus library, and there is separate process that reads those messages from dbus called xmonad-dbus which is used by polybar, could you please stop polybar or reconfigure so it's not used anymore to see which of the side causes high cpu usage, it seems like xmonad is generating too many messages which causes this cpu usage spike

**Comment by ironlungx** [comment]
yeah if i stop using it, my cpu usage drops down to 2-3%. This is irrelevant, but is there any way to log everything to a file say at `/tmp/xmlog`?

**Comment by troydm** [comment]
not sure what you mean by logging, you can play around with source code and write all messages to file or you can write your log hook for xmonad to check how many messages it generates per second, either way something is definitely wrong with either your dbus or xmonad or something in between, it can even be underlying haskell dbus library that xmonad-dbus uses under the hood

**Comment by ironlungx** [comment]
yeah, thanks I figured it out. Also I am 90% sure that the high cpu usage wasn't caused by your dbus module but another one for Bluetooth. Again I am not sure
